version: '3'
services:

  # NGINX
  nginx:
    build:
      context: ./images/nginx
      args:
        - NGINX_VERSION
        - TIMEZONE
    volumes:
      - ./www:/var/www
      - ./log/nginx:/var/log/nginx/
    ports:
      - "80"
    depends_on:
      - php-fpm
      - db
    networks:
      project_net:
        ipv4_address: ${NETWORK_WEB_IP}

  # PHP-FPM
  php-fpm:
    build:
      context: ./images/php-fpm
      args:
        - PHP_VERSION
        - TIMEZONE
    user: ${USER_ID}:${GROUP_ID}
    volumes:
      - ./www:/var/www
      - ./log/xdebug:/tmp/xdebug/
    environment:
      XDEBUG_CONFIG: "client_host=${NETWORK_HOST} log=/tmp/xdebug/xdebug.log"
      PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}"
    networks:
      project_net:
        ipv4_address: ${NETWORK_PHP_FPM_IP}
    working_dir: /var/www

  # DATABASE
  db:
    build:
      context: images/mysql
      args:
        - MYSQL_VERSION
        - TIMEZONE
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306"
    networks:
      project_net:
        ipv4_address: ${NETWORK_DB_IP}

networks:
  project_net:
    driver: bridge
    ipam:
      config:
        -   subnet: ${NETWORK_SUBNET}
